version: "3.8"
services:
  node-backend:
    build: ./node-backend
    ports:
      - "3000:3000"
    volumes:
      - ./node-backend:/app
    env_file:
      - ./node-backend/.env

  python-backend:
    build: ./python-backend
    ports:
      - "8000:8000"
    volumes:
      - ./python-backend:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
